config/routes.rb
Rails.application.routes.draw do
  resources :lists do
    resources :todos
  end

  resources :categories do
    resources :products
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Serve websocket cable requests in-process
  # mount ActionCable.server => '/cable'

  # root to: "lists#index"
  root to: "categories#index"
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.paginate(page: params[:page])
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:title, :tagline, :img_path)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_category.html.erb
<% cache category do %>
  <div style="float: left; width: 40%">
    <!-- h2><%= link_to category.title, category %></h2 -->
    <h2><%= category.title %></h2>
    
    <!--p>
      <%=image_tag("tops_sketch.jpg", size: "250x250")%>
    </p -->
    <%= link_to 'Product in this category', category_products_path(category) %>
    <p>
      <% my_img_url = "#{category.title.downcase}_main.jpg" %>
      <%=image_tag(my_img_url, size: "250x250")%>
    </p>
    <!-- %= link_to "Edit", edit_category_path(category)% -->

    <!--ul >
      <%= render partial: 'products/product', collection: category.products, cached: true %>
    </ul-->
  </div>
<% end %>

app/views/categories/_form.html.erb
<%= form_for(category) do |f| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
    <div class="field">
    <%= f.label :tagline %>
    <%= f.text_field :tagline %>
  </div>
    <div class="field">
    <%= f.label :img_path %>
    <%= f.text_field :img_path %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<%= Rails.application.config.cache_store %>

<p id="notice"><%= notice %></p>

<h1>Categories</h1>

<%= render partial: 'categories/category', collection: @categories %>

<br>

<%= link_to 'New Category', new_category_path %>

<%= will_paginate @categories %>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @category.title %>
</p>
<p>
  <strong>Tagline:</strong>
  <%= @category.tagline %>
</p>
<p>
  <% my_img_url = "#{@category.title.downcase}_main.jpg" %>
  <%=image_tag(my_img_url, size: "250x250")%>
</p>
<ul>
  <%= render partial: 'products/product', collection: @category.products, cached: true %>
</ul>
<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Product in this category', category_products_path(@category) %> |
<%= link_to 'New Product in this category', new_category_product_path(@category) %> |
<%= link_to 'Back', categories_path %>