config/routes.rb
Rails.application.routes.draw do
  resources :lists do
    resources :todos
  end

  resources :categories do
    resources :products
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Serve websocket cable requests in-process
  # mount ActionCable.server => '/cable'

  # root to: "lists#index"
  root to: "categories#index"
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category, touch: true
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_category
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = @category.products
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = @category.products.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to root_path, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to root_path, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to root_path, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_category
      @category = Category.find(params[:category_id])
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = @category.products.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white category through.
    def product_params
      params.require(:product).permit(:title, :description, :inr_price, :usd_price, :img_path, :column_1, :column_2, :column_3, :column_4, :column_5)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_for([@category, Product.new]) do |f| %>
  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
    <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>
    <div class="field">
    <%= f.label :inr_price %>
    <%= f.text_field :inr_price %>
  </div>
    <div class="field">
    <%= f.label :usd_price %>
    <%= f.text_field :usd_price %>
  </div>
    <div class="field">
    <%= f.label :img_path %>
    <%= f.text_field :img_path %>
  </div>
    </div>
    <div class="field">
    <%= f.label :column_1 %>
    <%= f.text_field :column_1 %>
  </div>
    </div>
    <div class="field">
    <%= f.label :column_2 %>
    <%= f.text_field :column_2 %>
  </div>
    </div>
    <div class="field">
    <%= f.label :column_3 %>
    <%= f.text_field :column_3 %>
  </div>
    </div>
    <div class="field">
    <%= f.label :column_4 %>
    <%= f.text_field :column_4 %>
  </div>
    </div>
    <div class="field">
    <%= f.label :column_5 %>
    <%= f.text_field :column_5 %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/_product.html.erb
<% cache product do %>
  <li><%= product.description %></li>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>
<% if @products.size > 0 %>
  <% product_type = @products[0].title
    category_name = product_type.split(" ")[0].upcase
  %>
  <h1><%= category_name %> Products Listing</h1>

  <table>
    <thead>
      <tr>
        <th>Description</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @products.each do |product| %>
        <tr>
          <!--% my_img_url = "#{product.title.downcase}_1.jpg" % -->
          <% my_img_url = "top_1.jpg" %>
          <td><%= product.description %></td>
          <td><%=image_tag(product.img_path, size: "50x50")%></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <h1>No Product in this Category please add them</h1>
<% end %>

<br>

<%= link_to 'New Product', new_category_product_path %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', todo: @product %>

<%= link_to 'Back', category_products_path %>

app/views/products/show.html.erb
<%= Rails.application.config.cache_store %>
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>
<% for i in 1..8 %>
  <p>
    <% my_img_url = "#{@product.img_path}.jpg" %>
    <%=image_tag(my_img_url, size: "360x240")%>
  </p>
<% end %>